using Microsoft.Extensions.Logging;

namespace VenueBooking.Modules.Identity.Logging;

/// <summary>
/// The Identity module's log events, declared once here rather than as ad-hoc strings at each call
/// site. Source-generated by <c>[LoggerMessage]</c>, so the message template and its arguments are
/// checked at compile time and no allocation happens when the level is disabled.
/// </summary>
/// <remarks>
/// Event ids are allocated per module from a 100-wide block — Identity owns 1000-1099 — so an id
/// in a log file identifies exactly one event without a lookup table.
/// <para>
/// Nothing here takes a password, a token or an email address as an argument. Auth events
/// identify a user by <see cref="Guid"/>; anything else belongs in the database, not the log.
/// </para>
/// </remarks>
internal static partial class IdentityLog
{
    [LoggerMessage(
        EventId = 1000,
        Level = LogLevel.Information,
        Message = "Seeded missing identity role {Role}")]
    public static partial void RoleSeeded(ILogger logger, string role);

    [LoggerMessage(
        EventId = 1001,
        Level = LogLevel.Error,
        Message = "Failed to seed identity role {Role}: {Reason}")]
    public static partial void RoleSeedingFailed(ILogger logger, string role, string reason);
}
